version: "3"
services:
  postgres:
    image: postgres:latest
    networks:
      - springnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=michal123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: springbootapp:latest
    networks:
      - springnet
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  springnet: